name: C/C++ CI

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
   
      
    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v4
      with:
        path: a.out
        key: ${{ runner.os }}-${{ hashFiles('main.c') }}
    
    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: gcc main.c

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit == 'true'
      run: echo HIT
   
